### ISSUE TITLE
Windows Build Failing

### ISSUE THREAD

**Issue by simondmorias** [DataThirstLtd/DBFS-Explorer#28]
Hey @saikksub - I'm getting this error when I run the build on Windows. Have some new Python dependancies been added? I'm not sure where to look to fix this. The mac build runs fine.

```
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=F:\Builds\_work\8\s\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=F:\Builds\_work\8\s\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v5.0-win32-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and electron@5.0.0 (electron-v5.0 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\ProgramData\Miniconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=F:\\Builds\\_work\\8\\s\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=F:\\Builds\\_work\\8\\s\\node_modules\\sqlite3\\lib\\binding\\electron-v5.0-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v5.0"
gyp ERR! cwd F:\Builds\_work\8\s\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=F:\Builds\_work\8\s\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=F:\Builds\_work\8\s\node_modules\sqlite3\lib\binding\electron-v5.0-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Builds\_work\8\s\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Builds\\_work\\8\\s\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Builds\_work\8\s\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by saikksub** [comment]
@simondmorias 

Please install `windows-build-tools` as global dependency:
``` bash
npm i -g windows-build-tools
```
Use power shell as administrator.

> Application doesn't have any dependency on python. This is required for rebuilding `sqlite3` with electron's version.
